# Generated by Django 6.0.2 on 2026-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
